### ISSUE TITLE
Include copy and pastable characters.

### ISSUE THREAD

**Issue by ChristopherKing42** [emojitracker/emojitrack-web#12]
Since these are just unicode characters, they can be copied and pasted. It would be useful if that option was made avaible. For example, http://www.emojitracker.com/details/1F602 corresponds to 😂. This would make it much easier to use.

NOTE: GitHub apparently doesn't let you copy and paste it right.

**Comment by mroth** [comment]
Hi @ChristopherKing42, I'm not sure I understand this request.  Currently we use native unicode characters (which should be copy-pastable) whenever we detect the browser supports them, and fall back to embedded images only in cases where (in theory) the browser does not support native Emoji.  Is this what you are referring to, or something else? Thanks!

**Comment by ChristopherKing42** [comment]
@mroth Oh, yes. I guess my browser didn't support them. (It supported some, but not all.)

**Comment by mroth** [comment]
Gotcha!  (Hopefully one day soon we will all be living in an full-emoji-support future and it will be possible to drop these compatibility hacks!)

**Comment by ChristopherKing42** [comment]
One small thing to consider would be detecting it character by character, but that may be overkill.
